name: CI

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile

    - name: Run build
      run: bun run build

    # - name: Run linter
    #   run: bun run lint

    # - name: Run tests
    #   run: bun run test
